### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by Xiaowenshi2000** [sanujitdash/Identification-of-Modulation-Techniques-using-ML#1]
作者您好！我在运行第6步代码history=model.fit(X_train, Y_train, batch_size=1024,epochs=100, validation_data=(X_test, Y_test),  callbacks=[EarlyStopping(patience=35, restore_best_weights = True)])时，遇到了这样错误：
Epoch 1/100
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-82-4a08e341d9cf> in <module>
----> 1 history=model.fit(X_train, Y_train, batch_size=1024,epochs=100, validation_data=(X_test, Y_test),  callbacks=[EarlyStopping(patience=35, restore_best_weights = True)])

D:\anaconda\lib\site-packages\keras\utils\traceback_utils.py in error_handler(*args, **kwargs)
     65     except Exception as e:  # pylint: disable=broad-except
     66       filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67       raise e.with_traceback(filtered_tb) from None
     68     finally:
     69       del filtered_tb

D:\anaconda\lib\site-packages\tensorflow\python\eager\execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     56   try:
     57     ctx.ensure_initialized()
---> 58     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     59                                         inputs, attrs, num_outputs)
     60   except core._NotOkStatusException as e:

InvalidArgumentError:  Conv2DCustomBackpropInputOp only supports NHWC.
	 [[node gradient_tape/model/conv2/Conv2D/Conv2DBackpropInput
 (defined at D:\anaconda\lib\site-packages\keras\optimizer_v2\optimizer_v2.py:464)
]] [Op:__inference_train_function_967]

Errors may have originated from an input operation.
Input Source operations connected to node gradient_tape/model/conv2/Conv2D/Conv2DBackpropInput:
In[0] gradient_tape/model/conv2/Conv2D/ShapeN:	
In[1] model/conv2/Conv2D/ReadVariableOp (defined at D:\anaconda\lib\site-packages\keras\layers\convolutional.py:231)	
In[2] gradient_tape/model/conv2/ReluGrad:

Operation defined at: (most recent call last)
>>>   File "D:\anaconda\lib\runpy.py", line 194, in _run_module_as_main
>>>     return _run_code(code, main_globals, None,
>>> 
>>>   File "D:\anaconda\lib\runpy.py", line 87, in _run_code
>>>     exec(code, run_globals)
>>> 
>>>   File "D:\anaconda\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
>>>     app.launch_new_instance()
>>> 
>>>   File "D:\anaconda\lib\site-packages\traitlets\config\application.py", line 845, in launch_instance
>>>     app.start()
>>> 
>>>   File "D:\anaconda\lib\site-packages\ipykernel\kernelapp.py", line 612, in start
>>>     self.io_loop.start()
>>> 
>>>   File "D:\anaconda\lib\site-packages\tornado\platform\asyncio.py", line 199, in start
>>>     self.asyncio_loop.run_forever()
>>> 
>>>   File "D:\anaconda\lib\asyncio\base_events.py", line 570, in run_forever
>>>     self._run_once()
>>> 
>>>   File "D:\anaconda\lib\asyncio\base_events.py", line 1859, in _run_once
>>>     handle._run()
>>> 
>>>   File "D:\anaconda\lib\asyncio\events.py", line 81, in _run
>>>     self._context.run(self._callback, *self._args)
>>> 
>>>   File "D:\anaconda\lib\site-packages\tornado\ioloop.py", line 688, in <lambda>
>>>     lambda f: self._run_callback(functools.partial(callback, future))
>>> 
>>>   File "D:\anaconda\lib\site-packages\tornado\ioloop.py", line 741, in _run_callback
>>>     ret = callback()
>>> 
>>>   File "D:\anaconda\lib\site-packages\tornado\gen.py", line 814, in inner
>>>     self.ctx_run(self.run)
>>> 
>>>   File "D:\anaconda\lib\site-packages\tornado\gen.py", line 775, in run
>>>     yielded = self.gen.send(value)
>>> 
>>>   File "D:\anaconda\lib\site-packages\ipykernel\kernelbase.py", line 365, in process_one
>>>     yield gen.maybe_future(dispatch(*args))
>>> 
>>>   File "D:\anaconda\lib\site-packages\tornado\gen.py", line 234, in wrapper
>>>     yielded = ctx_run(next, result)
>>> 
>>>   File "D:\anaconda\lib\site-packages\ipykernel\kernelbase.py", line 268, in dispatch_shell
>>>     yield gen.maybe_future(handler(stream, idents, msg))
>>> 
>>>   File "D:\anaconda\lib\site-packages\tornado\gen.py", line 234, in wrapper
>>>     yielded = ctx_run(next, result)
>>> 
>>>   File "D:\anaconda\lib\site-packages\ipykernel\kernelbase.py", line 543, in execute_request
>>>     self.do_execute(
>>> 
>>>   File "D:\anaconda\lib\site-packages\tornado\gen.py", line 234, in wrapper
>>>     yielded = ctx_run(next, result)
>>> 
>>>   File "D:\anaconda\lib\site-packages\ipykernel\ipkernel.py", line 306, in do_execute
>>>     res = shell.run_cell(code, store_history=store_history, silent=silent)
>>> 
>>>   File "D:\anaconda\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
>>>     return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
>>> 
>>>   File "D:\anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 2894, in run_cell
>>>     result = self._run_cell(
>>> 
>>>   File "D:\anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 2940, in _run_cell
>>>     return runner(coro)
>>> 
>>>   File "D:\anaconda\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
>>>     coro.send(None)
>>> 
>>>   File "D:\anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 3165, in run_cell_async
>>>     has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
>>> 
>>>   File "D:\anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 3357, in run_ast_nodes
>>>     if (await self.run_code(code, result,  async_=asy)):
>>> 
>>>   File "D:\anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 3437, in run_code
>>>     exec(code_obj, self.user_global_ns, self.user_ns)
>>> 
>>>   File "<ipython-input-64-41b3e4b85c3e>", line 1, in <module>
>>>     history=model.fit(X_train, Y_train, epochs=100, validation_data=(X_test, Y_test), batch_size=1024, callbacks=[EarlyStopping(patience=35, restore_best_weights = True)])
>>> 
>>>   File "D:\anaconda\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
>>>     return fn(*args, **kwargs)
>>> 
>>>   File "D:\anaconda\lib\site-packages\keras\engine\training.py", line 1216, in fit
>>>     the batch size, or 1 if that cannot be determined. If x is a
>>> 
>>>   File "D:\anaconda\lib\site-packages\keras\engine\training.py", line 878, in train_function
>>>     self.loss_tracker = tf.keras.metrics.Mean(name='loss')
>>> 
>>>   File "D:\anaconda\lib\site-packages\keras\engine\training.py", line 867, in step_function
>>>     """Compute the total loss, validate it, and return it.
>>> 
>>>   File "D:\anaconda\lib\site-packages\keras\engine\training.py", line 860, in run_step
>>>     loss = self.compute_loss(x, y, y_pred, sample_weight)
>>> 
>>>   File "D:\anaconda\lib\site-packages\keras\engine\training.py", line 816, in train_step
>>>     # is a valid use when such loss from `add_loss` exists and target does not.
>>> 
>>>   File "D:\anaconda\lib\site-packages\keras\optimizer_v2\optimizer_v2.py", line 530, in minimize
>>>     """
>>> 
>>>   File "D:\anaconda\lib\site-packages\keras\optimizer_v2\optimizer_v2.py", line 583, in _compute_gradients
>>>     with tf.name_scope(self._name + "/gradients"):
>>> 
>>>   File "D:\anaconda\lib\site-packages\keras\optimizer_v2\optimizer_v2.py", line 464, in _get_gradients
>>> 
请问您在编写代码的时候是否遇到这样的问题了呢？如果有的话是否可以讲解一下，十分感谢

**Comment by sanujitdash** [comment]
Are you running this on CPU or GPU? If you're running it on CPU, then this issue crops up. Please try to run this using a GPU and see if the issue resolves. Use GPU available online if you don't have it on your system. Hope your Issue resolves speedily. Regards.

你是在 CPU 还是 GPU 上运行它？如果你在 CPU 上运行它，那么这个问题就会出现。请尝试使用 GPU 运行它，看看问题是否解决。如果您的系统上没有 GPU，请使用在线提供的 GPU。希望您的问题能尽快解决。问候。
